### ISSUE TITLE
Day2에 있는 방식이 이해가 잘 안되Yo~

### ISSUE THREAD

**Issue by nosent79** [yamoo9/jQuery-Class#3]
index.html 에서 js/build.js 를 호출하고

build.js 에는 e(t,n,r) ~로 시작되는 코드로

``` js
    /**
     * --------------------------------
     * 모듈 정의
     * --------------------------------
     */
    var instructor = {
        name: 'Jinuk',
        nickname: 'nosent',
        getFullName: function() {
            return name;
        }
    };

    // 모듈 출력
    module.exports = instructor;

},{}],2:[function(require,module,exports){
    /**
     * --------------------------------
     * CommonJS 방식
     * --------------------------------
     */
    // 모듈 호출
    var instructor = require('./instructor.js');

    console.log(instructor.name);
},{"./instructor.js":1}]},{},[2]);
```

---

[질문]

모듈 호출 부분에 분명 instructor.js를 사용하는데 build.js 의 instructor 관련 부분을 주석처리하면 undefined라고 나오네요.

원리가 궁금합니다 ㅋㅋㅋㅋ (기억이 안나요)

**Comment by yamoo9** [comment]
질문의 답변으로 아래 코드 구문이 핵심이라고 이야기드릴 수 있습니다.

``` js
// 모듈 출력
module.exports = instructor;
```

Node.js 환경에서는 module.exports를 이용하여 Javascript 파일 간 모듈 공유가 가능합니다.

`instructor` 변수 메모리에 할당된 객체 값을 `module.exports`에 참조하면, 다른 Javascript 파일에서 `require('./instructor.js')`명령을 수행하여 외부의 모듈 코드를 참조/호출하여 사용할 수 있게 됩니다.

정리하면...

`build.js`의 `instructor` 관련 부분을 주석 처리했을 때 `undefined`라고 나오는 이유는 
`module.export`를 통해 내보낼 `instructor` 객체가 존재하지 않기 때문입니다.

**Comment by nosent79** [comment]
쌤~ 답변감사합니다.

추가적인 질문은 이따 강의시간에 다시 질문 드릴께요 ㅋㅋㅋㅋ
