### ISSUE TITLE
15일차 수업내용이 궁금해요~

### ISSUE THREAD

**Issue by nosent79** [yamoo9/jQuery-Class#6]
마지막 수업에 참석하지 못해서 너무 아쉽네요.  ^^;;;;

지금 github에서 15일차를 보고 있는데 수업 때 사용했을 법한 소스파일이 올라오지 않은거 같아요~~

확인 좀 해주세요 ;)

ex ) src/html 폴더자체가 없어요~~

ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

jQueryPluginStartKit 에 들어있었군요.............. 해결했습니다.

**Comment by yamoo9** [comment]
넵 찾으셨군요 ^ㅡ^
